Refactor fetching of trusted-firmware-m
ARMmbed/mbed-os-tf-m-regression-tests pull request #100
Opened 2021-04-20 11:54 UTC by LDong-Arm

This PR does the following:
* Use trusted-firmware-m's own version control - The build system of trusted-firmware-m tracks specific versions of dependencies. This _fixes our nightly CI failure_ due to the latest psa-arch-tests not compiling with the latest trusted-firmware-m.
* Clean up version tracking of trusted-firmware-m - Now the only thing to fetch is https://git.trustedfirmware.org/TF-M/trusted-firmware-m.git. Note: Not backward compatible with TF-M v1.2, but the tfm_latest_integration_check branch is CI-only, and some other parts of the scripts don't work with TF-M v1.2 anyway.
* Handle switching of git remote - We renamed remotes in the previous commit and a few times before, but the failure (due to remote not found) isn't obvious to users.

2021-04-20 15:10 UTC, Patater requested changes

2021-04-20 16:08 UTC, LDong-Arm commented on psa_builder.py
> -    # If the remote repo is changed, please delete tfm/repos/trusted-firmware-m.
> Does this mean I can switch remotes for trusted-firmware-m now?

Yes. Prier to this change, the script didn't support multiple remotes or when a remote was renamed locally (e.g. origin -> upstream).

Now I actually think it's better not to rely on remote names. Fetching by URL directly is most reliable and saves us troubles. I'll change it.

2021-04-20 16:45 UTC, LDong-Arm commented on psa_builder.py
> -    # If the remote repo is changed, please delete tfm/repos/trusted-firmware-m.
Commit message updated without code change.

2021-04-21 08:43 UTC, Patater approved these changes

2021-04-21 08:44 UTC, merged