psa_builder.py: catch command not found error
ARMmbed/mbed-os-tf-m-regression-tests pull request #55
Opened 2020-11-09 11:18 UTC by LDong-Arm

@ARMmbed/mbed-os-security

2020-11-09 11:23 UTC, LDong-Arm commented
Code format check failed in CI, but it doesn't say what format it expects, or what the formatter command is?

2020-11-09 12:18 UTC, LDong-Arm commented
@evedon FYI

2020-11-09 14:51 UTC, jainvikas8 commented
@LDong-Arm 
```
Run lgeiger/black-action@v1.0.1
  with:
    args: . -l 79 --check
```

2020-11-09 15:00 UTC, LDong-Arm commented
> @LDong-Arm
> 
> ```
> Run lgeiger/black-action@v1.0.1
>   with:
>     args: . -l 79 --check
> ```

It's a GitHub Action, triggered in a Docker container. Would be better to dump the format diff in CI, so users wouldn't need to install all the tools to reproduce it locally...

2020-11-09 15:11 UTC, LDong-Arm commented on .github/workflows/main.yml
> +        args: ". -l 79 --diff --color --check"
Now, CI prints the diff so users can easily fix any format errors 🙂

2020-12-14 15:41 UTC, LDong-Arm commented
This is from over a month ago, shall we get it in?

2020-12-15 12:55 UTC, jainvikas8 requested changes
Please rebase this PR... So that it can run the Travis job

2020-12-15 13:17 UTC, LDong-Arm commented
> Please rebase this PR... So that it can run the Travis job

Done. Let's wait for CI.

2020-12-15 13:54 UTC, jainvikas8 approved these changes

2020-12-16 15:27 UTC, merged